imjuni/ctix

.circleci/config.yml
example/type04/tsconfig.json
jest.config.cjs
package-lock.json
package.json
src/tools/__tests__/clean.test.ts
src/tools/__tests__/tsfile.test.ts
src/tools/__tests__/write.test.ts
src/tools/misc.ts
src/tools/tsfiles.ts
test.spec.cjs

* Add jest test order
* Mod beforeAll, afterEach hook in write and clean test

Fix CircleCI broken

---

package-lock.json
package.json
src/ctix.ts
src/tools/__tests__/config.test.ts
src/tools/cticonfig.ts
src/tools/write.ts

* Fix useRootDir option always enabled

Fix useRootDir always enabled

---

package-lock.json
package.json

Rollback chalk version

---

package-lock.json
package.json

* fix audit warn
* version bumps: json5 2.2.0 > 2.2.1

Fix audit warn

---

README.md
package-lock.json
package.json

* collect option effect description

Fix README.md content

---

src/modules/getDescendantExportInfo.ts

* Enhance sorting of descendant export

Enhance sorting of descendant export

---

README.md
docs/MigrationGuide.md
package-lock.json
package.json
src/modules/createDescendantIndex.ts
src/modules/getDirPaths.ts

* change ignore logic
* add content in README.md and MigrationGuide.md

Change ignore logic

---

example/type06/.ctiignore
example/type06/case001.ts
example/type06/case002.ts
example/type06/case003.ts
example/type06/fast-maker/ChildlikeCls.ts
example/type06/fast-maker/FlakyCls.ts
example/type06/fast-maker/WhisperingCls.ts
example/type06/fast-maker/__tests__/juvenile.test.ts
example/type06/fast-maker/carpenter/DiscussionCls.ts
example/type06/fast-maker/carpenter/MakeshiftCls.ts
example/type06/tsconfig.json
package-lock.json
package.json
src/compilers/__tests__/compilers.test.ts
src/compilers/getExportedName.ts
src/ignores/__tests__/ignore.test.ts
src/testenv/env.ts
tsconfig.json

* add BindingElement syntax: https://github.com/imjuni/ctix/issues/29
* add example06
* version bumps: 1.1.0 > 1.1.1

Add BindingElement syntax

---

package-lock.json
package.json
src/cli/progress.ts
src/cli/reasoner.ts
src/validations/__tests__/expects/expect-validateExportDuplication.ts
src/validations/__tests__/expects/expect-validateFileNameDuplication.ts
src/validations/validateExportDuplication.ts
src/validations/validateFileNameDuplication.ts
src/writes/indexFileWrite.ts
tsconfig.json
webpack.config.dev.cjs
webpack.config.prod.cjs

* add type declaration ctix.d.ts
* apply webpack multi-compiler configuration
* change package: chalk > colors
* fix security vulnerabaliliy

Add type declaration

---

package-lock.json
package.json
src/cli/progress.ts
src/cli/reasoner.ts
src/validations/__tests__/expects/expect-validateExportDuplication.ts
src/validations/__tests__/expects/expect-validateFileNameDuplication.ts
src/validations/validateExportDuplication.ts
src/validations/validateFileNameDuplication.ts
src/writes/indexFileWrite.ts

* module change colors > chalk

Fix colors.js infinity loop

---

package-lock.json
package.json
src/ctix.ts
src/modules/getDirPaths.ts

* include .gitignore apply glob algorithms
* error type fix

Enhance performance getDirPaths

---

README.md

Enhance README.md content

---

README.md
src/compilers/getExportInfo.ts
src/compilers/getIsIsolatedModules.ts

This PR is a proposal for #52.

#52 Consider all exported declarations in the scope

---

package-lock.json
package.json
src/configs/preLoadConfig.ts

* fix bug don't display help content
* add new command deps-diff
* deps
* prod * add minimist: 1.2.7
* dev
* add @types/minimist: 1.2.2
* add deps-diff: 1.0.0

Fix bug don't display help content

---

package-lock.json
package.json
src/compilers/__tests__/compilers.test.ts
src/compilers/getTypeScriptProject.ts
src/compilers/tsMorphProjectOption.ts
src/ctix.ts
src/modules/__tests__/create.test.ts
src/modules/__tests__/modules.test.ts
src/modules/__tests__/single.test.ts
src/validations/__tests__/validation.test.ts

* skip node_modules loading
* skip resolve file dependencies
* migrate testcase

Performance tunning

---

src/compilers/__tests__/compilers.test.ts
src/compilers/__tests__/expects/expect-getExportInfos-module-wildcard.ts
src/compilers/getExportInfo.ts
src/compilers/interfaces/IIdentifierWithNode.ts
src/validations/validateExportDuplication.ts

* remove regular expression for prevent duplication
* enhance exportInfo for module declaration
* additional process for module declaration and dynamic pattern

enhance module declaration duplication processing logic

---

.github/workflows/ci.yml
README.md

* add new badge: github action, codecov

Add new badge

---

README.md

- [change] renamed `index.ts` file to barrel
- [add] Added barrel file description and barrel file documentation

Change: renamed `index.ts` file to barrel

---

README.md
package.json
pnpm-lock.yaml

chore(release): `2.4.4` > `2.4.5`

---

package.json
pnpm-lock.yaml

feat(deps): upgrade dependencies

---

.github/workflows/ci.yml
CODE_OF_CONDUCT.md
README.md
src/modules/commands/bundling.ts
src/modules/commands/creating.ts
src/modules/commands/moduling.ts

- add: show a warning message in case of empty results
- enhance documentation: add include/exclude options
- add code of conduct

feat(ui): show a warning message in case of empty results

---

src/cli/interfaces/IInitQuestionAnswer.ts
src/cli/questions/askInitOptions.ts
src/configs/loadConfig.ts
src/configs/modules/getDefaultInitAnswer.ts
src/configs/modules/json/readJsonConfig.ts
src/configs/modules/json/safeJsonc.ts
src/modules/commands/initializing.ts

- enhance configuration reading
- configuration can be read from the `.ctirc`, `tsconfig.json`, `package.json`
- enhance initialization command
- initialization command can select the position: `.ctirc`, `tsconfig.json`, `package.json`

feat(config): diversification of configuration

---

README.md

feat(doc): enhance README.md documentation

---

package.json

chore(release): `2.6.2` > `2.6.3`

---

package.json

chore(release): `2.6.3` > `2.6.4`

---

package.json

chore(release): `2.6.4` > `2.7.0`

---

src/configs/modules/json/getString.ts

- fix: build error by getString

fix(chore): fix build error
